# Generated by Django 3.2.8 on 2021-10-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AddField(
            model_name='article',
            name='content_de',
            field=models.TextField(default='test', verbose_name='content de'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(default='test', verbose_name='content en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='slug_de',
            field=models.SlugField(default='slug', verbose_name='slug de'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(default='slud-de', verbose_name='slug en'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
