# Generated by Django 3.2.8 on 2021-10-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20211013_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_de',
            field=models.CharField(default='test', max_length=255, verbose_name='title de'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(default='test', max_length=255, verbose_name='title en'),
            preserve_default=False,
        ),
    ]
