# Generated by Django 3.2.8 on 2021-10-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20211013_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image thumb'),
        ),
    ]
